spring.application.name=petbook
spring.datasource.url=jdbc:postgresql://localhost:5432/petbook
spring.datasource.username=postgres
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.hbm2ddl.auto=validate
